- name: Check & install python
  hosts: all
  become: true
  gather_facts: False
  tasks:
    - name: Install python 4 ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
