---
- name: Configure hosts & deploy app
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.15.225
  tasks:
    - name: update mongo config
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongo
    
    - name: fetch latest reddit-app
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag

    - name: Add puma unit file
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: add config for db conn
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag
 
    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag
    
  handlers:
    - name: restart mongo
      become: true
      service: name=mongod state=restarted
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
